### PR TITLE
Changed use of deprecated doctrine/orm connect method to use getNativeConnection method

### PR DESCRIPTION
**Pull request by Victor-Truhanovich**
Changed use of deprecated doctrine/orm connect method to use getNativeConnection method

### CODE REVIEW

**Review by Arhell — APPROVED** [review]

**Comment by W0rma** [comment]
I tested the change locally and it does indeed fix the following deprecation warning when using this module together with `doctrine/dbal:3.7.1`:

> Public access to Connection::connect() is deprecated. (Connection.php:366 called by Doctrine2.php:260, https://github.com/doctrine/dbal/issues/4966, package doctrine/dbal)

**Review by W0rma — APPROVED** [review]

**Comment by W0rma** [comment]
@Naktibalda Are there any plans to tag a new release containing this fix?

**Comment by W0rma** [comment]
DBAL v4 has been released: https://github.com/doctrine/dbal/releases/tag/4.0.0

I have prepared https://github.com/Codeception/module-doctrine2/pull/78 which adds support for ORM v3 + DBAL v4 and cherry-picked the fix from this PR.

**Comment by TavoNiievez** [comment]
Replaced by https://github.com/Codeception/module-doctrine/pull/26

**Pull request closed without merging**
